// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package bot

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6bbfce87DecodeGithubComKramerdustIndefibotBot(in *jlexer.Lexer, out *ButtonData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Word":
			out.Word = string(in.String())
		case "Next":
			out.Next = int(in.Int())
		case "AuidoAsked":
			out.AuidoAsked = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6bbfce87EncodeGithubComKramerdustIndefibotBot(out *jwriter.Writer, in ButtonData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Word\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Word))
	}
	{
		const prefix string = ",\"Next\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Next))
	}
	{
		const prefix string = ",\"AuidoAsked\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.AuidoAsked))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ButtonData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6bbfce87EncodeGithubComKramerdustIndefibotBot(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ButtonData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6bbfce87EncodeGithubComKramerdustIndefibotBot(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ButtonData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6bbfce87DecodeGithubComKramerdustIndefibotBot(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ButtonData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6bbfce87DecodeGithubComKramerdustIndefibotBot(l, v)
}
